version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: hw4


  db:
    image: postgres:15
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: hw4

    ports:
      - "5432:5432"